security:
    enable_authenticator_manager: true
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            #anonymous: true
            lazy: true
            logout:
                path: PapyrillioPapPalBundle_Logout
                target: PapyrillioPapPalBundle_Home # where to redirect after logout
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    encoders:
        App\Entity\User:
            algorithm: auto

    access_control:
        - { path: '^/admin', roles: ROLE_ADMIN }
        - { path: '^/profile', roles: ROLE_USER }
