PapyrillioPapPalBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: PapyrillioPapPalBundle:Default:index }

# Special

PapyrillioPapPalBundle_hgvChanges:
    pattern:  /hgvChanges/{jourFixe}
    defaults: { _controller: PapyrillioPapPalBundle:Default:hgvChanges, jourFixe: null }
    requirements:
        jourFixe:  \d{4}-\d{2}-\d{2}


# Sample

PapyrillioPapPalBundle_SampleList:
    pattern:  /sample/list
    defaults: { _controller: PapyrillioPapPalBundle:Sample:list }

PapyrillioPapPalBundle_SampleGallery:
    pattern:  /sample/gallery
    defaults: { _controller: PapyrillioPapPalBundle:Sample:list }

PapyrillioPapPalBundle_SampleShow:
    pattern:  /sample/show/{id}
    defaults: { _controller: PapyrillioPapPalBundle:Sample:show }

PapyrillioPapPalBundle_SampleTm:
    pattern:  /tm/{tm}
    defaults: { _controller: PapyrillioPapPalBundle:Sample:tm }

PapyrillioPapPalBundle_SampleHgv:
    pattern:  /hgv/{hgv}
    defaults: { _controller: PapyrillioPapPalBundle:Sample:hgv }

PapyrillioPapPalBundle_SampleDdb:
    pattern:  /ddb/{ddb}
    defaults: { _controller: PapyrillioPapPalBundle:Sample:ddb }

# Sample Admin

PapyrillioPapPalBundle_SampleSetMasterThumbnail:
    pattern:  /sample/setMasterThumbnail/{id}
    defaults: { _controller: PapyrillioPapPalBundle:Sample:setMasterThumbnail }

PapyrillioPapPalBundle_SampleUploadImage:
    pattern:  /sample/uploadImage/{id}
    defaults: { _controller: PapyrillioPapPalBundle:Sample:uploadImage }

PapyrillioPapPalBundle_SampleDeleteImage:
    pattern:  /sample/deleteImage/{id}/{image}
    defaults: { _controller: PapyrillioPapPalBundle:Sample:deleteImage }

PapyrillioPapPalBundle_SampleDelete:
    pattern:  /sample/delete/{id}
    defaults: { _controller: PapyrillioPapPalBundle:Sample:delete }

PapyrillioPapPalBundle_SampleDeleteThumbnail:
    pattern:  /sample/deleteThumbnail/{id}/{thumbnail}
    defaults: { _controller: PapyrillioPapPalBundle:Sample:deleteThumbnail }

PapyrillioPapPalBundle_SampleRotateThumbnail:
    pattern:  /sample/rotateThumbnail/{id}/{thumbnail}/{direction}
    defaults: { _controller: PapyrillioPapPalBundle:Sample:rotateThumbnail }

# Static pages

PapyrillioPapPalBundle_Home:
    pattern:  /
    defaults: { _controller: PapyrillioPapPalBundle:Default:home }

PapyrillioPapPalBundle_Contact:
    pattern:  /contact
    defaults: { _controller: PapyrillioPapPalBundle:Default:contact }
