PapyrillioPapPalBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: PapyrillioPapPalBundle:Default:index }

# Sample

PapyrillioPapPalBundle_SampleList:
    pattern:  /sample/list
    defaults: { _controller: PapyrillioPapPalBundle:Sample:list }

PapyrillioPapPalBundle_SampleGallery:
    pattern:  /sample/gallery
    defaults: { _controller: PapyrillioPapPalBundle:Sample:list }

PapyrillioPapPalBundle_SampleShow:
    pattern:  /sample/show/{id}
    defaults: { _controller: PapyrillioPapPalBundle:Sample:show }

# Sample Admin

PapyrillioPapPalBundle_SampleSetMasterThumbnail:
    pattern:  /sample/setMasterThumbnail/{id}
    defaults: { _controller: PapyrillioPapPalBundle:Sample:setMasterThumbnail }

PapyrillioPapPalBundle_SampleUploadImage:
    pattern:  /sample/uploadImage/{id}
    defaults: { _controller: PapyrillioPapPalBundle:Sample:uploadImage }

PapyrillioPapPalBundle_SampleDelete:
    pattern:  /sample/delete/{id}
    defaults: { _controller: PapyrillioPapPalBundle:Sample:delete }
