parameters:
#    papyrillio_pap_pal.example.class: Papyrillio\PapPalBundle\Example

services:
#    papyrillio_pap_pal.example:
#        class: %papyrillio_pap_pal.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
