parameters:
#    papyrillio_pap_pal.example.class: Papyrillio\PapPalBundle\Example
    papyrillio_pap_pal.image_cropper.class: Papyrillio\PapPalBundle\Service\ImageCropper

services:
#    papyrillio_pap_pal.example:
#        class: %papyrillio_pap_pal.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    papyrillio_pap_pal.image_cropper:
        class: %papyrillio_pap_pal.image_cropper.class%
