Papyrillio\PapPalBundle\Entity\Comment:
    type: entity
    table: comment
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        postingDate:
            type: datetime
        post:
            type: text

    manyToOne:
        sample:
            targetEntity: Sample
            inversedBy: comments
            joinColumn:
                name: sample_id
                referencedColumnName: id
                nullable: false
        user:
            targetEntity: Papyrillio\UserBundle\Entity\User
            inversedBy: comments
            joinColumn:
                name: user_id
                referencedColumnName: id
                nullable: false
    # don't forget to init the collection in entity __construct() method